version: "3.8"

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: zibtek-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - zibtek-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: zibtek-backend
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - DATABASE_URL=sqlite:///./data/chatbot.db
      - CORS_ORIGINS=["http://localhost:3000"]
    volumes:
      - ./backend/data:/app/data
    depends_on:
      - qdrant
    networks:
      - zibtek-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: zibtek-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - zibtek-network
    restart: unless-stopped

volumes:
  qdrant_data:
    driver: local

networks:
  zibtek-network:
    driver: bridge

